# Generated by Django 3.2.19 on 2023-08-24 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_voetbalspelers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Voetbalspelers',
        ),
    ]
